version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      
  # Flutter
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Android
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"

