on: push
name: Build, Release
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - name: Build Linux
        run: flutter build linux --release
      - name: Build Web
        run: flutter build web --release --base-href "/visualtimer/"
      - name: Deploy Web
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
      - name: Artifact Linux
        uses: actions/upload-artifact@v4
        with:
          name: visualtimer_linux
          path: build/linux/x64/release/bundle/
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: |
          cd artifacts/visualtimer_linux
          zip -r ../visualtimer_linux.zip ./
      - uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: ./artifacts/visualtimer_linux.zip